import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ContentTemplate } from '../types';

export function generatePDF(schedule: ContentTemplate, niche: string): void {
  const doc = new jsPDF();
  
  // Set background color for all pages
  const pageCount = schedule.weeks.length;
  for (let i = 0; i < pageCount; i++) {
    doc.setPage(i + 1);
    doc.setFillColor(14, 3, 20); // Dark purple background
    doc.rect(0, 0, doc.internal.pageSize.width, doc.internal.pageSize.height, 'F');
  }

  schedule.weeks.forEach((week, weekIndex) => {
    if (weekIndex > 0) {
      doc.addPage();
    }

    // Week header
    doc.setTextColor(186, 252, 99); // Neon green
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text(`Week ${week.weekNumber}`, 14, 20);

    // Content table
    autoTable(doc, {
      startY: 30,
      head: [[
        'Day',
        'Content',
        'Talking Points',
        'Hooks',
        'Notes'
      ]],
      body: week.days.map(day => [
        day.day,
        `${day.overallIdea}\n${day.contentType}`,
        day.talkingPoints.join('\n'),
        day.hooks.join('\n'),
        day.additionalNotes
      ]),
      theme: 'grid',
      styles: {
        fontSize: 10,
        textColor: [255, 255, 255],
        fillColor: [14, 3, 20],
        cellPadding: 8,
        lineColor: [186, 252, 99],
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [186, 252, 99],
        textColor: [14, 3, 20],
        fontSize: 12,
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 40 },
        2: { cellWidth: 45 },
        3: { cellWidth: 45 },
        4: { cellWidth: 35 },
      },
      margin: { left: 14, right: 14 },
    });

    // Footer
    doc.setTextColor(186, 252, 99);
    doc.setFontSize(10);
    doc.text(
      `Generated by Content Labs - Page ${weekIndex + 1} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  });

  // Download the PDF
  doc.save(`${niche.toLowerCase().replace(/\s+/g, '-')}-content-calendar.pdf`);
}